.PHONY: vga_hsync_tb
vga_hsync_tb:
	xelab --prj prj/vga_hsync_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.vga_hsync_tb

.PHONY: vga_vsync_tb
vga_vsync_tb:
	xelab --prj prj/vga_vsync_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.vga_vsync_tb

.PHONY: vga_pixel_clock_tb
vga_pixel_clock_tb:
	xelab --prj prj/vga_pixel_clock_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.vga_pixel_clock_tb

.PHONY: vga_simple_grid_tb
vga_simple_grid_tb:
	xelab --prj prj/vga_simple_grid_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.vga_simple_grid_tb

.PHONY: vga_simple_test_tb
vga_simple_test_tb:
	xelab --prj prj/vga_simple_test_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.vga_simple_test_tb

.PHONY: framebuffer36E1x8
framebuffer36E1x8:
	xelab --prj prj/framebuffer36E1x8.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.framebuffer36E1x8

.PHONY: video_pipeline_test
video_pipeline_test:
	xelab --prj prj/video_pipeline_test.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.video_pipeline_test

.PHONY: video_pipeline_tb
video_pipeline_tb:
	xelab --prj prj/video_pipeline_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.video_pipeline_tb

.PHONY: vga_state_fsm_tb
vga_state_fsm_tb:
	xelab --prj prj/vga_state_fsm_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.vga_state_fsm_tb

